version: 2

references:

  test-steps: &test-steps
    - checkout
    - run: pip install --user tox
    - run: ~/.local/bin/tox

jobs:

  test-3.5:
    docker:
      - image: circleci/python:3.5
    steps: *test-steps
    environment:
      TOXENV: py35

  test-3.6:
    docker:
      - image: circleci/python:3.6
    steps: *test-steps
    environment:
      TOXENV: py36

  test-3.7:
    docker:
      - image: circleci/python:3.7
    steps: *test-steps
    environment:
      TOXENV: py37

  test-3.8:
    docker:
      - image: circleci/python:3.8.0a4
    steps: *test-steps
    environment:
      TOXENV: py38

  test-pypy3.5:
    docker:
      - image: pypy:3.5
    steps: *test-steps
    environment:
      TOXENV: pypy35

  test-pypy3.6:
    docker:
      - image: pypy:3.6
    steps: *test-steps
    environment:
      TOXENV: pypy36

workflows:
  version: 2

  # Build on push
  on_push:
    jobs:
      - test-3.5
      - test-3.6
      - test-3.7
      - test-3.8
      - test-pypy3.5
      - test-pypy3.6

  # Build master every week on Monday at 04:00 am
  weekly:
    triggers:
      - schedule:
          cron: "0 4 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - test-3.5
      - test-3.6
      - test-3.7
